"""Add bot_replied_to_mention to Drop

Revision ID: 0fe836b7797e
Revises: 
Create Date: 2025-05-03 00:37:52.278895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe836b7797e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_replied_to_mention', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.drop_column('bot_replied_to_mention')

    # ### end Alembic commands ###
