"""Add oracle_active and oracle_start_time to WaveTracking

Revision ID: 78dc5562e711
Revises: ddd8b015164d
Create Date: 2025-07-23 09:15:25.698202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dc5562e711'
down_revision = 'ddd8b015164d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wave_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oracle_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('oracle_start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wave_tracking', schema=None) as batch_op:
        batch_op.drop_column('oracle_start_time')
        batch_op.drop_column('oracle_active')

    # ### end Alembic commands ###
