"""Add oracle protocol fields to WaveTracking

Revision ID: ddd8b015164d
Revises: 0fe836b7797e
Create Date: 2025-07-23 08:04:36.694003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd8b015164d'
down_revision = '0fe836b7797e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('wave_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('bot_replied_to_mention')

    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_identities_handle'), ['handle'], unique=True)
        batch_op.create_index(batch_op.f('ix_identities_normalized_handle'), ['normalized_handle'], unique=False)

    with op.batch_alter_table('wave', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('wave_tracking', schema=None) as batch_op:
        batch_op.alter_column('wave_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('last_activity_check',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wave_tracking', schema=None) as batch_op:
        batch_op.alter_column('last_activity_check',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('wave_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('wave', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identities_normalized_handle'))
        batch_op.drop_index(batch_op.f('ix_identities_handle'))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_replied_to_mention', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('wave_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
